# -*- coding: utf-8 -*-
"""av3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159ku5L6ndlWjI_7tcqW9owaMC-o3RwQ8
"""

!pip install scikit-learn seaborn tensorflow

import numpy as np
from tensorflow.keras.datasets import mnist
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

# 1) Carregar o MNIST
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#  print some information on the data
print(X_train.shape)
print(y_train.shape)


# 2) Reduzir para (N, 784)
X_train = X_train.reshape((X_train.shape[0], -1))
X_test = X_test.reshape((X_test.shape[0], -1))

import random
# Exibe as 5 primeiras imagens
plt.figure(figsize=(10, 2))
for i in range(5):
    numero = random.randint(0, 1000)
    plt.subplot(1, 5, i+1)
    plt.imshow(X_train[numero].reshape(28, 28), cmap="gray") # Reshape back to 28x28 for display
    plt.title(f"Label: {y_train[numero]}")
    plt.axis("off")

plt.show()

# 3) Normalização
X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

# 4) Criar o modelo de Regressão Logística (Softmax)
model = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    penalty="l2",
    max_iter=150,
    verbose=1,
    n_jobs=-1
)

# 5) Treinamento
print("Treinando modelo...")
model.fit(X_train, y_train)

# 6) Predições
y_pred = model.predict(X_test)

# 7) Avaliação
print("\n========== RESULTADOS ==========")
print("Acurácia:", accuracy_score(y_test, y_pred))

print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

# 8) Matriz de confusão
plt.figure(figsize=(10,8))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=False, cmap="Blues")
plt.title("Matriz de Confusão — MNIST (Regressão Logística)")
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.show()

import cv2
import numpy as np

# carregar imagem
img = cv2.imread("oi_to.png", cv2.IMREAD_GRAYSCALE)

# Verificar se a imagem foi carregada com sucesso
if img is None:
    print("Erro: Não foi possível carregar a imagem. Verifique o caminho do arquivo.")
else:
    # Redimensionar a imagem usando cv2.resize
    img = cv2.resize(img, (28, 28))

    # Converter para float32 e normalizar
    img = img.astype("float32") / 255.0
    img = img.reshape(1, 784)
    img = 1 - img
    plt.figure(figsize=(15, 3))
    plt.imshow(img.reshape(28, 28), cmap="gray")
    plt.axis("off")

    pred = model.predict(img)
    print("Número reconhecido:", pred[0])



import random

# Selecionar 5 índices aleatórios do conjunto de testes
random_indices = random.sample(range(len(X_test)), 5)

plt.figure(figsize=(15, 3))
for i, index in enumerate(random_indices):
    plt.subplot(1, 5, i + 1)
    # Redimensionar a imagem para 28x28 para exibição
    plt.imshow(X_test[index].reshape(28, 28), cmap="gray")
    plt.title(f"Real: {y_test[index]}\nPrevisto: {y_pred[index]}")
    plt.axis("off")

plt.suptitle("5 Exemplos Aleatórios do MNIST (Real vs. Previsto)", fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Ajusta o layout para a super-título
plt.show()